/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Dialog.java to edit this template
 */
package GUI;

import ClassModel.Kategori;
import ClassModel.Produk;

/**
 * Dialog untuk input data produk baru.
 * Digunakan sebagai form tambahan dari FormProduk.
 * 
 * @author Admin
 */
public class DialogInputProduk extends java.awt.Dialog {
    private FormProduk parentForm;        // Form utama yang memanggil dialog ini
    private Dao.ProdukDAO produkDao;      // Untuk akses database produk
    private java.util.List<Kategori> listKategori; // Data kategori dari database
    
     /**
     * Constructor default 
     */
    public DialogInputProduk(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    /**
     * Constructor utama yang dipake.
     * 
     * @param parent form utama (FormProduk)
     * @param modal true biar dialog modal (gak bisa klik form lain)
     * @param produkDao objek DAO untuk operasi database produk
     */
    public DialogInputProduk(FormProduk parent, boolean modal, Dao.ProdukDAO produkDao) {
        super(parent, modal);
        this.parentForm = parent;
        this.produkDao = produkDao;
        
        initComponents();
        loadKategoriData(); // Isi combobox dengan data kategori dari DB
        setLocationRelativeTo(parent); // Biar muncul di tengah form
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtharga = new javax.swing.JTextField();
        txtstock = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnsave = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmbkategoriproduk = new javax.swing.JComboBox<>();

        setName("Insert Produk"); // NOI18N
        setTitle("Insert Produk");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jLabel1.setText("Nama");

        jLabel2.setText("Kategori Produk");

        jLabel3.setText("Harga");

        jLabel4.setText("Stock");

        btnsave.setText("Save");
        btnsave.addActionListener(this::btnsaveActionPerformed);

        jLabel5.setText(":");

        jLabel6.setText(":");

        jLabel7.setText(":");

        jLabel8.setText(":");

        cmbkategoriproduk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnsave)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtharga)
                            .addComponent(txtstock)
                            .addComponent(txtnama)
                            .addComponent(cmbkategoriproduk, 0, 141, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(cmbkategoriproduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtstock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(btnsave)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    /**
     * Tombol Save: simpan produk baru ke database.
     * Validasi yang dilakukan:
     * 1. Cek field kosong
     * 2. Cek tipe data angka (NumberFormatException)
     * 3. Cek nilai negatif
     */
    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // Ambil semua input dari form
        String nama = txtnama.getText().trim();
        int kategoriIndex = cmbkategoriproduk.getSelectedIndex();
        String hargaStr = txtharga.getText().trim();
        String stokStr = txtstock.getText().trim();

        // VALIDASI 1: Cek apakah ada data yang kosong
        if (nama.isEmpty() || kategoriIndex == -1 || hargaStr.isEmpty() || stokStr.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Semua data harus diisi!");
            return;
        }

        try {
            // VALIDASI 2: Konversi harga dan stok ke angka
            int harga = Integer.parseInt(hargaStr);
            int stok = Integer.parseInt(stokStr);

            // VALIDASI 3: Cek apakah nilai negatif
            if (harga < 0 || stok < 0) {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Harga dan Stok tidak boleh negatif!");
                return;
            }

            // Ambil kategori yang dipilih dari combobox
            Kategori katTerpilih = listKategori.get(kategoriIndex);

            // Bungkus data ke objek Produk
            Produk p = new Produk();
            p.setNama(nama);
            p.setKodeProduk(katTerpilih.getKode());
            p.setHarga(harga);
            p.setStock(stok);

            // Simpan ke database
            if (produkDao.insert(p)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Produk baru berhasil ditambahkan!");
                parentForm.loadDataToTable(); // Refresh tabel di form utama
                this.dispose(); // Tutup dialog
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Gagal menyimpan produk ke database.");
            }

        } catch (NumberFormatException ex) {
            // Kalau harga atau stok bukan angka
            javax.swing.JOptionPane.showMessageDialog(this, "Harga dan Stok harus berupa angka!");
        }
    }//GEN-LAST:event_btnsaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogInputProduk dialog = new DialogInputProduk(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsave;
    private javax.swing.JComboBox<String> cmbkategoriproduk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtstock;
    // End of variables declaration//GEN-END:variables

    /**
     * Ambil data kategori dari database dan isi ke combobox.
     * Format yang ditampilkan: "Nama Kategori - Brand"
     * Contoh: "Elektronik - Samsung"
     */
    private void loadKategoriData() {
        Dao.KategoriDAO katDao = new Dao.KategoriDAO();
        
        // Ambil semua data kategori dari database
        listKategori = katDao.getAllKategori();
    
        // Hapus isi default combobox (yang dibuat NetBeans)
        cmbkategoriproduk.removeAllItems(); 
    
        // Masukkan data kategori satu per satu ke combobox
        for (Kategori kat : listKategori) {
            cmbkategoriproduk.addItem(kat.getKategori() + " - " + kat.getBrand());
        }
    }
}
