/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import Dao.KategoriDAO;
import ClassModel.Kategori;
import javax.swing.JOptionPane;

/**
 * Form untuk mengelola data kategori.
 * Fitur: tambah, edit, hapus, dan lihat data kategori.
 * 
 * @author Admin
 */
public class FormKategori extends javax.swing.JFrame {
    // Objek DAO buat akses database kategori
    private KategoriDAO kategoriDao = new KategoriDAO();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormKategori.class.getName());

    /**
     * Constructor utama.
     * Menyiapkan form, tampilkan di tengah layar, langsung tampilin data.
     */
    public FormKategori() {
        initComponents();            // Buat komponen GUI
        setLocationRelativeTo(null); // Tengahin layar
        loadKategoriToTable();       // Tampilin data dari database
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblkategori = new javax.swing.JTable();
        btndelete = new javax.swing.JButton();
        btninsert = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnload = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Form Kategori");

        tblkategori.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode", "Kategori", "Brand"
            }
        ));
        jScrollPane1.setViewportView(tblkategori);

        btndelete.setText("Delete");
        btndelete.addActionListener(this::btndeleteActionPerformed);

        btninsert.setText("Insert");
        btninsert.addActionListener(this::btninsertActionPerformed);

        btnload.setText("Load");
        btnload.addActionListener(this::btnloadActionPerformed);

        btnupdate.setText("Update");
        btnupdate.addActionListener(this::btnupdateActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnload)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btninsert)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnupdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btndelete)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnload)
                        .addComponent(btnupdate)
                        .addComponent(btninsert)
                        .addComponent(btndelete)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Tombol Insert: tambah kategori baru.
     * - Input nama kategori
     * - Input brand
     * - Cek duplikat
     * - Simpan ke database
     */
    private void btninsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninsertActionPerformed
        // Minta input nama kategori
        String namaKategori = javax.swing.JOptionPane.showInputDialog(
            this, 
            "Masukkan Nama Kategori:", 
            "Input Kategori", 
            javax.swing.JOptionPane.PLAIN_MESSAGE
        );
        if (namaKategori == null) return; // User klik cancel
    
        // Validasi: nama kategori gak boleh kosong
        namaKategori = namaKategori.trim();
        if (namaKategori.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Nama Kategori tidak boleh kosong!");
            return;
        }

        // Minta input brand
        String brand = javax.swing.JOptionPane.showInputDialog(
            this, 
            "Masukkan Nama Brand:", 
            "Input Brand", 
            javax.swing.JOptionPane.PLAIN_MESSAGE
        );
        if (brand == null) return; // User klik cancel
    
        // Validasi: brand gak boleh kosong
        brand = brand.trim();
        if (brand.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Brand tidak boleh kosong!");
            return;
        }

        // Cek apakah kombinasi kategori + brand sudah ada di database
        if (kategoriDao.isDuplikat(namaKategori, brand)) {
            javax.swing.JOptionPane.showMessageDialog(
                this, 
                "Gagal! Kategori '" + namaKategori + "' dengan Brand '" + brand + "' sudah ada.", 
                "Data Duplikat", 
                javax.swing.JOptionPane.ERROR_MESSAGE
            );
            return; 
        }

        // Bungkus data ke objek Kategori
        Kategori k = new Kategori();
        k.setKategori(namaKategori);
        k.setBrand(brand);

        // Simpan ke database
        if (kategoriDao.insert(k)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Kategori baru berhasil ditambahkan!");
            loadKategoriToTable(); // Refresh tabel
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal menyimpan data ke database.");
        }
    }//GEN-LAST:event_btninsertActionPerformed
    
     /**
     * Tombol Delete: hapus kategori yang dipilih.
     * - Cek apakah kategori masih dipakai produk
     * - Konfirmasi sebelum hapus
     */
    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
    // Cek apakah ada baris yang dipilih
        int selectedRow = tblkategori.getSelectedRow();
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih kategori yang akan dihapus.");
            return;
        }

        // Ambil data dari baris yang dipilih
        int kode = (int) tblkategori.getValueAt(selectedRow, 0);
        String namaKategori = (String) tblkategori.getValueAt(selectedRow, 1);

        // Cek apakah kategori masih dipakai oleh produk
        if (kategoriDao.isDipakaiProduk(kode)) {
            javax.swing.JOptionPane.showMessageDialog(
                this, 
                "Kategori '" + namaKategori + "' masih digunakan oleh produk, tidak bisa dihapus.", 
                "Gagal Hapus", 
                javax.swing.JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        // Konfirmasi penghapusan
        int confirm = javax.swing.JOptionPane.showConfirmDialog(
            this, 
            "Yakin ingin menghapus kategori '" + namaKategori + "'?", 
            "Konfirmasi Hapus", 
            javax.swing.JOptionPane.YES_NO_OPTION
        );
        
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            if (kategoriDao.delete(kode)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Kategori berhasil dihapus.");
                loadKategoriToTable(); // Refresh tabel
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Gagal menghapus kategori.");
            }
        }
    }//GEN-LAST:event_btndeleteActionPerformed
    
    /**
     * Tombol Load: refresh data di tabel.
     * Dipakai kalau ada perubahan data dari luar.
     */
    private void btnloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloadActionPerformed
        loadKategoriToTable();
    }//GEN-LAST:event_btnloadActionPerformed
     
    /**
     * Tombol Update: edit kategori yang dipilih.
     * - Input kategori baru
     * - Input brand baru
     * - Cek duplikat (kecuali sama persis dengan data lama)
     * - Simpan perubahan ke database
     */
    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
    // Cek apakah ada baris yang dipilih
        int selectedRow = tblkategori.getSelectedRow();
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih kategori yang akan diupdate.");
            return;
        }

        // Ambil data lama dari baris yang dipilih
        int kode = (int) tblkategori.getValueAt(selectedRow, 0);
        String kategoriLama = (String) tblkategori.getValueAt(selectedRow, 1);
        String brandLama = (String) tblkategori.getValueAt(selectedRow, 2);

        // Minta input kategori baru (dengan default data lama)
        String kategoriBaru = javax.swing.JOptionPane.showInputDialog(
            this, 
            "Masukkan Nama Kategori baru:", 
            kategoriLama
        );
        if (kategoriBaru == null) return; // User klik cancel
        kategoriBaru = kategoriBaru.trim();
        if (kategoriBaru.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Nama Kategori tidak boleh kosong.");
            return;
        }

        // Minta input brand baru (dengan default data lama)
        String brandBaru = javax.swing.JOptionPane.showInputDialog(
            this, 
            "Masukkan Brand baru:", 
            brandLama
        );
        if (brandBaru == null) return; // User klik cancel
        brandBaru = brandBaru.trim();
        if (brandBaru.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Brand tidak boleh kosong.");
            return;
        }

        // Cek duplikat (kecuali datanya sama persis dengan yang lama)
        if (kategoriDao.isDuplikat(kategoriBaru, brandBaru)) {
            if (!(kategoriLama.equals(kategoriBaru) && brandLama.equals(brandBaru))) {
                javax.swing.JOptionPane.showMessageDialog(
                    this, 
                    "Kombinasi Kategori dan Brand sudah ada!", 
                    "Duplikat", 
                    javax.swing.JOptionPane.ERROR_MESSAGE
                );
                return;
            }
        }

        // Bungkus data ke objek Kategori
        Kategori k = new Kategori(kode, kategoriBaru, brandBaru);
        
        // Simpan perubahan ke database
        if (kategoriDao.update(k)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Kategori berhasil diupdate.");
            loadKategoriToTable(); // Refresh tabel
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal mengupdate kategori.");
        }
    }//GEN-LAST:event_btnupdateActionPerformed

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        // Set the Nimbus look and feel 
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        // If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        // For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        // Create and display the form 
        java.awt.EventQueue.invokeLater(() -> new FormKategori().setVisible(true));
    }
    */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btninsert;
    private javax.swing.JButton btnload;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblkategori;
    // End of variables declaration//GEN-END:variables

    /**
     * Load data kategori dari database ke dalam tabel.
     * Diambil semua terus dimasukin ke baris-baris tabel.
     */
    private void loadKategoriToTable() {
        // Ambil model tabelnya
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblkategori.getModel();
    
        // Kosongkan isi tabel dulu
        model.setRowCount(0); 

        // Ambil semua data kategori dari database
        java.util.List<Kategori> list = kategoriDao.getAllKategori();

        // Masukkan satu per satu ke tabel
        for (Kategori k : list) {
            Object[] row = {
                k.getKode(),
                k.getKategori(),
                k.getBrand()
            };
            model.addRow(row);
        }
    }
}
