/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import ClassModel.Kategori;
import ClassModel.Produk;
import javax.swing.JOptionPane;
import javax.swing.JDialog;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;
import java.awt.BorderLayout;
import java.awt.GridBagLayout;
import java.awt.GridBagConstraints;
import java.awt.Insets;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.Dimension;

/**
 * Form utama untuk mengelola data produk.
 * Fitur: tambah, edit, hapus, dan lihat data produk.
 * Terintegrasi dengan FormKategori untuk manajemen kategori.
 * 
 * @author Admin
 */
public class FormProduk extends javax.swing.JFrame {
    // Objek DAO buat akses database produk
    private Dao.ProdukDAO produkDao = new Dao.ProdukDAO();
    private java.util.List<ClassModel.Produk> listProduk; // List produk terakhir yang di-load
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormProduk.class.getName());

     /**
     * Constructor utama.
     * Menyiapkan form dan semua komponennya.
     */
    public FormProduk() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnkategori = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablelistproduk = new javax.swing.JTable();
        btnload = new javax.swing.JButton();
        btninsert = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnabout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnkategori.setText("Kategori");
        btnkategori.addActionListener(this::btnkategoriActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("List Produk :");

        tablelistproduk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode", "Nama Product", "Harga", "Stock", "Kategori", "Brand"
            }
        ));
        jScrollPane1.setViewportView(tablelistproduk);

        btnload.setText("Load");
        btnload.addActionListener(this::btnloadActionPerformed);

        btninsert.setText("Insert");
        btninsert.addActionListener(this::btninsertActionPerformed);

        btnupdate.setText("Update");
        btnupdate.addActionListener(this::btnupdateActionPerformed);

        btndelete.setText("Delete");
        btndelete.addActionListener(this::btndeleteActionPerformed);

        btnabout.setText("About");
        btnabout.addActionListener(this::btnaboutActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnabout)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnkategori)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnload)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btninsert)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnupdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btndelete)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnkategori)
                    .addComponent(jLabel1)
                    .addComponent(btnabout))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnload)
                    .addComponent(btninsert)
                    .addComponent(btnupdate)
                    .addComponent(btndelete))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Tombol Load: refresh data produk di tabel.
     * Ambil data terbaru dari database.
     */
    private void btnloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloadActionPerformed
        // Mengambil data dari DB
        loadDataToTable();
    }//GEN-LAST:event_btnloadActionPerformed
    
    /**
     * Tombol Kategori: buka form manajemen kategori.
     * Biar user bisa tambah/edit/hapus kategori.
     */
    private void btnkategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkategoriActionPerformed
        // Membuat objek jendel baru untuk Form Kategori
        GUI.FormKategori formKat = new GUI.FormKategori();

        // Memunculkan Form Kategori ke layar
        formKat.setVisible(true);
    }//GEN-LAST:event_btnkategoriActionPerformed
    
    /**
     * Tombol Delete: hapus produk yang dipilih.
     * - Cek apakah ada baris yang dipilih
     * - Konfirmasi sebelum hapus
     */
    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // Cek apakah ada baris yang dipilih
        int selectedRow = tablelistproduk.getSelectedRow();
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih produk yang akan dihapus.");
            return;
        }

        // Ambil kode produk dari baris yang dipilih
        int kodeProduk = (int) tablelistproduk.getValueAt(selectedRow, 0);
        
        // Konfirmasi penghapusan
        int confirm = javax.swing.JOptionPane.showConfirmDialog(
            this, 
            "Yakin ingin menghapus produk ini?", 
            "Konfirmasi Hapus", 
            javax.swing.JOptionPane.YES_NO_OPTION
        );
        
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            if (produkDao.delete(kodeProduk)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Produk berhasil dihapus.");
                loadDataToTable(); // Refresh tabel
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Gagal menghapus produk.");
            }
        }
    }//GEN-LAST:event_btndeleteActionPerformed
    
     /**
     * Tombol Insert: buka dialog input produk baru.
     * User akan mengisi data produk di dialog terpisah.
     */
    private void btninsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninsertActionPerformed
        // Panggil form dialog
        GUI.DialogInputProduk dialog = new GUI.DialogInputProduk(this, true, produkDao);
        dialog.setVisible(true);
    }//GEN-LAST:event_btninsertActionPerformed
    
      /**
     * Tombol Update: buka dialog edit produk yang dipilih.
     * - Cek apakah ada baris yang dipilih
     * - Ambil data produk dari database
     * - Buka dialog update dengan data yang ada
     */
    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        int selectedRow = tablelistproduk.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih produk yang akan diupdate.");
            return;
        }

        int kodeProduk = (int) tablelistproduk.getValueAt(selectedRow, 0);
        
        Produk p = produkDao.getProdukById(kodeProduk);
        if (p == null) {
            JOptionPane.showMessageDialog(this, "Data produk tidak ditemukan.");
            return;
        }

        showUpdateDialog(p);
    }

    /**
     * Method untuk menampilkan dialog update produk internal.
     * 
     * @param produkLama Data produk yang akan diedit
     */
    private void showUpdateDialog(Produk produkLama) {
    // Buat JDialog internal
    JDialog updateDialog = new JDialog(this, "Update Produk", true);
    
    // Ambil data kategori dari database
    Dao.KategoriDAO katDao = new Dao.KategoriDAO();
    java.util.List<Kategori> listKategori = katDao.getAllKategori();
    
    // === Buat komponen-komponen form ===
    JLabel jLabel1 = new JLabel("Nama");
    JTextField txtnama = new JTextField();
    txtnama.setText(produkLama.getNama());
    
    JLabel jLabel2 = new JLabel("Kategori Produk");
    JComboBox<String> cmbkategoriproduk = new JComboBox<>();
    for (Kategori kat : listKategori) {
        cmbkategoriproduk.addItem(kat.getKategori() + " - " + kat.getBrand());
    }
    // Set selected index sesuai produk lama
    for (int i = 0; i < listKategori.size(); i++) {
        if (listKategori.get(i).getKode() == produkLama.getKodeProduk()) {
            cmbkategoriproduk.setSelectedIndex(i);
            break;
        }
    }
    
    JLabel jLabel3 = new JLabel("Harga");
    JTextField txtharga = new JTextField();
    txtharga.setText(String.valueOf(produkLama.getHarga()));
    
    JLabel jLabel4 = new JLabel("Stock");
    JTextField txtstock = new JTextField();
    txtstock.setText(String.valueOf(produkLama.getStock()));
    
    JButton btnupdate = new JButton("Update");
    
    JLabel jLabel5 = new JLabel(":");
    JLabel jLabel6 = new JLabel(":");
    JLabel jLabel7 = new JLabel(":");
    JLabel jLabel8 = new JLabel(":");
    
    // === Layout menggunakan GroupLayout (sama seperti DialogInputProduk) ===
    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(updateDialog.getContentPane());
    updateDialog.getContentPane().setLayout(layout);
    
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(btnupdate)
                .addGroup(layout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(jLabel1))
                    .addGap(37, 37, 37)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtharga)
                        .addComponent(txtstock)
                        .addComponent(txtnama)
                        .addComponent(cmbkategoriproduk, 0, 141, Short.MAX_VALUE))))
            .addContainerGap())
    );
    
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel5))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel2)
                .addComponent(jLabel6)
                .addComponent(cmbkategoriproduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel3)
                .addComponent(jLabel7)
                .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txtstock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel8)
                .addComponent(jLabel4))
            .addGap(18, 18, 18)
            .addComponent(btnupdate)
            .addGap(0, 8, Short.MAX_VALUE))
    );
    
    // === Event handler tombol Update ===
    btnupdate.addActionListener((ActionEvent e) -> {
        String nama = txtnama.getText().trim();
        String hargaStr = txtharga.getText().trim();
        String stokStr = txtstock.getText().trim();
        String selectedItem = (String) cmbkategoriproduk.getSelectedItem();

        if (nama.isEmpty() || selectedItem == null || hargaStr.isEmpty() || stokStr.isEmpty()) {
            JOptionPane.showMessageDialog(updateDialog, "Semua data harus diisi!");
            return;
        }

        Kategori kategoriTerpilih = null;
        for (Kategori kat : listKategori) {
            String comboText = kat.getKategori() + " - " + kat.getBrand();
            if (comboText.equals(selectedItem)) {
                kategoriTerpilih = kat;
                break;
            }
        }

        if (kategoriTerpilih == null) {
            JOptionPane.showMessageDialog(updateDialog, "Kategori tidak valid.");
            return;
        }

        try {
            int harga = Integer.parseInt(hargaStr);
            int stok = Integer.parseInt(stokStr);
            
            if (harga < 0 || stok < 0) {
                JOptionPane.showMessageDialog(updateDialog, "Harga dan Stok tidak boleh negatif.");
                return;
            }

            produkLama.setNama(nama);
            produkLama.setKodeProduk(kategoriTerpilih.getKode());
            produkLama.setHarga(harga);
            produkLama.setStock(stok);

            if (produkDao.update(produkLama)) {
                JOptionPane.showMessageDialog(updateDialog, "Produk berhasil diupdate!");
                loadDataToTable();
                updateDialog.dispose();
            } else {
                JOptionPane.showMessageDialog(updateDialog, "Gagal mengupdate produk.");
            }
            
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(updateDialog, "Harga dan Stok harus berupa angka!");
        }
    });
    
    // === Event handler untuk close dialog via X button ===
    updateDialog.addWindowListener(new WindowAdapter() {
        @Override
        public void windowClosing(WindowEvent e) {
            updateDialog.dispose();
        }
    });
    
    // === Tampilkan dialog ===
    updateDialog.pack();
    updateDialog.setLocationRelativeTo(this);
    updateDialog.setVisible(true);
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnaboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaboutActionPerformed
          // Create a formatted string with team member information
    StringBuilder aboutText = new StringBuilder();
    aboutText.append("=== TEAM PRODUK MANAGEMENT SYSTEM ===\n\n");
    aboutText.append("Daftar Anggota Tim:\n\n");
    aboutText.append("1. Rendra Adnan Farid     (25104410036) - Project Lead & Tester & Documentation & Backend Developer\n");
    aboutText.append("2. M. Rizki Desca F.      (25104410041) - Database Developer & DAO\n");
    aboutText.append("3. Ema Netasari           (25104410052) - Frontend Developer (GUI)\n");
    aboutText.append("4. Nahrul Mubarok         (25104410062) - Backend Developer\n");
    aboutText.append("5. Gladis Ayu Diapitaloka (25104410073) - UI/UX Design & Documentation\n");
    aboutText.append("6. Adelia Wahyu Bima Sakti (25104410094) - Frontend Developer (GUI)\n\n");
    aboutText.append("=== Aplikasi Manajemen Produk ===\n");
    aboutText.append("Versi 1.0\n");
    aboutText.append("© 2026 - All Rights Reserved");
    
    // Display the information in a dialog
    JOptionPane.showMessageDialog(
        this, 
        aboutText.toString(), 
        "Tentang Aplikasi", 
        JOptionPane.INFORMATION_MESSAGE
    );
    }//GEN-LAST:event_btnaboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormProduk().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnabout;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btninsert;
    private javax.swing.JButton btnkategori;
    private javax.swing.JButton btnload;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablelistproduk;
    // End of variables declaration//GEN-END:variables

    /**
     * Load data produk dari database ke dalam tabel.
     * Data yang diambil sudah lengkap dengan kategori dan brand (hasil JOIN).
     * Dipanggil saat form dibuka, setelah insert/update/delete.
     */
    void loadDataToTable() {
        // Ambil model tabelnya
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tablelistproduk.getModel();
    
        // Kosongkan isi tabel dulu
        model.setRowCount(0);
    
        // Ambil semua data produk dari database (lengkap dengan JOIN kategori)
        this.listProduk = produkDao.getAllProduk();
        
        // Masukkan satu per satu ke tabel
        for (ClassModel.Produk p : listProduk) {
            Object[] row = {
                p.getKode(),
                p.getNama(),
                p.getHarga(),
                p.getStock(),
                p.getNamaKategori(), // Hasil JOIN dari tabel kategori
                p.getBrand()         // Hasil JOIN dari tabel kategori
            };
            model.addRow(row);
        }
    }
}


